FROM node:alpine

WORKDIR /app

COPY --from=workspace .yarn/ ./.yarn
COPY --from=workspace .yarnrc.yml ./
COPY --from=workspace package.json ./
COPY --from=workspace yarn.lock ./


COPY --from=workspace ./server/graph ./server/graph
COPY --from=workspace ./contract/roleverse ./contract/roleverse
COPY --from=workspace ./lib/format-config ./lib/format-config

RUN yarn workspaces focus @roleverse/root @roleverse/server-graph @roleverse/format-config @roleverse/contract-roleverse

RUN yarn workspace @roleverse/contract-roleverse compile
RUN yarn workspace @roleverse/server-graph build

CMD yarn workspace @roleverse/server-graph create-local && yarn workspace @roleverse/server-graph deploy-local