FROM node:alpine

WORKDIR /app

COPY --from=workspace .yarn/ ./.yarn
COPY --from=workspace .yarnrc.yml ./
COPY --from=workspace package.json ./
COPY --from=workspace yarn.lock ./


COPY --from=workspace ./contract/roleverse ./contract/roleverse
COPY --from=workspace ./lib/format-config ./lib/format-config

RUN apk --no-cache add curl

RUN yarn workspaces focus @roleverse/root @roleverse/contract-roleverse @roleverse/format-config

RUN chmod +x ./contract/roleverse/entrypoint.sh

CMD ["sh", "./contract/roleverse/entrypoint.sh"]